a = input('Digite algo:')
print('Qual o tipo primitivo de {0}?'.format(a) , type(a)) 
print('Tem apenas espaço em {0}?'.format(a) , a.isspace())
print('Tem apenas números em {0}?'.format(a) , a.isnumeric())
print('Tem apenas letras em {0}?'.format(a) , a.isalpha())
print('Tem letras e números {0}?'.format(a) , a.isalnum())
print('{0} está em letras maiúsculas?'.format(a), a.isupper())
print('{0} está em letras minúsculas?'.format(a) , a.islower())
print('{0} tem letras maiúsculas e minúsculas?'.format(a) , a.istitle())
