pl = input('Digite algo:')
print('O tipo primitivo desse valor é:' , type(pl))
print('Só tem espaços?', pl.isspace())
print('Tem apenas letras?', pl.isalpha())
print('Tem apenas números?', pl.isnumeric())
print('Está em maiúsculo?', pl.isupper())
print('Está em minúsculo?', pl.islower())
print('Tem números e letras?', pl.isalnum())
print('Está capitalizada?', pl.istitle())
